#
#  Author: Hari Sekhon
#  Date: 2021-01-18 18:15:39 +0000 (Mon, 18 Jan 2021)
#
#  vim:ts=4:sts=4:sw=4:noet
#
#  https://github.com/HariSekhon/Kubernetes-templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

SHELL = /usr/bin/env bash

.PHONY: default
default: deploy
	@:

.PHONY: deploy
deploy:
	@./deploy.sh
